spring:
  application:
    name: oauth2-server
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://106.12.137.47:3306/autho?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: lyp19891117
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

server:
  port: 9000


mybatis:
  type-aliases-package: novli.nacos.spring.security.oauth2.server.domain
  mapper-locations: classpath:mapper/*.xml
